apiVersion: apps/v1
kind: Deployment
metadata:
  name: game-2048
  labels:
    app: game-2048
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: game-2048
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: game-2048
    spec:
      containers:
      - image: alexwhen/docker-2048
        imagePullPolicy: Always
        name: game-2048
        ports:
        - containerPort: 8501
          protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  name: game-2048
spec:
  type: LoadBalancer
  selector:
    app: game-2048
  ports:
   -  protocol: TCP
      port: 80
      targetPort: 8501
